FinalProject - Carpooling/Models/Trip/TripViewModel.cs
using CarPooling.Data.Models.Enums;
using CarPooling.Service.ResponseModels;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CarPooling.Models.Trip
{
    public class TripViewModel
    {
        public int TripId { get; set; }
        public int StartingPointId { get; set; }
        public List<SelectListItem> StartingPointList { get; set; }
        public string StartingPoint { get; set; }
        public int EndingPointId { get; set; }
        public List<SelectListItem> EndingPointList { get; set; }
        public string EndingPoint { get; set; }

        public TripStatus Status { get; set; }
        public SelectList TripStatuses { get; set; }
        [DataType(DataType.Date)]
        public DateTime DepartureDate { get; set; }
        [DataType(DataType.Time)]
        public DateTime DepartureTime { get; set; }
        public int DriverId { get; set; }
        public string DriverName { get; set; }
        public string DriverPhone { get; set; }
        [Required]
        [StringLength(30, MinimumLength = 2, ErrorMessage = "Value for {0} must be between {1} and {2}.")]
        public string CarColor { get; set; }
        [Required]
        [StringLength(30, MinimumLength = 2, ErrorMessage = "Value for {0} must be between {1} and {2}.")]
        public string CarModel { get; set; }
        public bool AirConditioner { get; set; }
        public bool PetsAllowed { get; set; }
        public bool SmokingAllowed { get; set; }
        public int FreeSeats { get; set; }
        public IEnumerable<UserResponseModel> Passengers { get; set; }
        public IEnumerable<UserResponseModel> Candidates { get; set; }

        //new
        public TripWeatherResponseModel Weather { get; set; }

    }
}

FinalProject - Carpooling/Controllers/AddressController.cs
using CarPooling.Helpers;
using CarPooling.Models;
using CarPooling.Models.Address;
using CarPooling.Service.Services.Contracts;
using CarPooling.Services.Exceptions;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CarPooling.Controllers
{
    public class AddressController : Controller
    {
        private readonly IAddressService addressService;
        private readonly IWebModelMapper modelMapper;
        private readonly IUserService userService;

        public AddressController(IAddressService addressService, IWebModelMapper modelMapper, IUserService userService)
        {
            this.addressService = addressService;
            this.modelMapper = modelMapper;
            this.userService = userService;
        }
        [HttpGet]
        [MyAuthorisation(Role = "User,Admin")]
        public async Task<IActionResult> Create()
        {
            var newAddress = new AddressViewModel();
            newAddress.Cities = await GetCities();
            return View(newAddress);
        }
        [HttpPost]
        [MyAuthorisation(Role = "User,Admin")]
        public async Task<IActionResult> Create(AddressViewModel newAddress)
        {
            var id = int.Parse(this.HttpContext.Session.GetString("UserId"));
            if (!ModelState.IsValid)
            {
                return Json(new { html = await Renderer.RenderViewAsync(this, "Create", newAddress, false) });
            }
            try
            {
                var address = modelMapper.ToModel(newAddress);
                address.UserUsesId = id;
                var createdAddress = await addressService.CreateAsync(address);
                return Json(new { html = $"{createdAddress.Street}", value = $"{createdAddress.AddressId}" });
            }
            catch (DuplicateEntityException e)
            {
                var Error = new ErrorViewModel
                {
                    ImageUrl = "~/assets/customImages/Icons/ErrorIcons/AuthenticationIcon.png",
                    StatusCode = 409,
                    Message = e.Message
                };
                return View("Error", Error);
            }
        }
        private async Task<SelectList> GetCities()
        {
            var cities = await this.addressService.GetAllCitiesAsync();
            return new SelectList(cities, "CityId", "Name");
        }
        private async Task<List<SelectListItem>> GetAddresses()
        {
            var id = int.Parse(this.HttpContext.Session.GetString("UserId"));
            var addresses = await this.userService.TakeUserAddresses(id);
            var addressesList = addresses.Select(x => new SelectListItem()
            {
                Value = x.AddressId.ToString(),
                Text = $"{x.Street} , {x.City}"
            }).ToList();

            return addressesList;
        }
    }
}

FinalProject - Carpooling/Controllers/TripsController.cs
using CarPooling.Data.Models.Enums;
using CarPooling.Helpers;
using CarPooling.Models;
using CarPooling.Models.Trip;
using CarPooling.Service.Constants;
using CarPooling.Service.Services.Contracts;
using CarPooling.Services.Exceptions;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CarPooling.Controllers
{
    public class TripsController : Controller
    {
        private readonly ITripService tripService;
        private readonly IUserService userService;
        private readonly IWebModelMapper modelMapper;

        public TripsController(ITripService tripService, IUserService userService, IWebModelMapper modelMapper)
        {
            this.tripService = tripService;
            this.userService = userService;
            this.modelMapper = modelMapper;
        }
        public async Task<IActionResult> Index()
        {
            var paginatedTrips = await tripService.GetAllPaginatedTripsAsync(1);
            return View(paginatedTrips);
        }
        [HttpPost]
        public async Task<IActionResult> GetAllPaginatedTrips(int page)
        {
            var result = await tripService.GetAllPaginatedTripsAsync(page);
            return Json(new { html = await Renderer.RenderViewAsync(this, "_Table", result, true) });
        }

        public async Task<IActionResult> Details(int id)
        {
            try
            {
                if (HttpContext.Session.Keys.Contains("UserId"))
                {
                    var userId = int.Parse(this.HttpContext.Session.GetString("UserId"));
                    var user = this.userService.GetByIdAsync(userId);
                    RedirectToAction("SetSessionStrings", "Account", await user);
                }
                var trip = await tripService.GetByIdAsync(id);
                var tripViewModel = this.modelMapper.ToViewModel(trip);

                var weatherModel = await tripService.GetWeather(trip);
                tripViewModel.Weather = weatherModel;

                return View(tripViewModel);
            }
            catch (EntityNotFoundException e)
            {
                var Error = new ErrorViewModel
                {
                    ImageUrl = "~/assets/customImages/Icons/ErrorIcons/NotFoundIcon.png",
                    StatusCode = 404,
                    Message = e.Message
                };
                return View("Error", Error);
            }
        }

        [HttpGet]
        [MyAuthorisation(Role = "User,Admin")]
        public async Task<IActionResult> Edit(int id)
        {
            var driverId = int.Parse(this.HttpContext.Session.GetString("UserId"));
            try
            {
                var tripToUpdate = await tripService.GetByIdAsync(id);
                if (tripToUpdate.DriverId != driverId)
                {
                    var Error = new ErrorViewModel
                    {
                        ImageUrl = "~/assets/customImages/Icons/ErrorIcons/AuthenticationIcon.png",
                        StatusCode = 401,
                        Message = ExceptionMessages.YouCannotDoThat
                    };
                    return View("Error", Error);
                }
                var tripViewModel = modelMapper.ToViewModel(tripToUpdate);
                return await TripView(id, tripViewModel);
            }
            catch (EntityNotFoundException e)
            {
                var Error = new ErrorViewModel
                {
                    ImageUrl = "~/assets/customImages/Icons/ErrorIcons/NotFoundIcon.png",
                    StatusCode = 404,
                    Message = e.Message
                };
                return View("Error", Error);
            }
        }

        [HttpPost]
        [MyAuthorisation(Role = "User,Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("StartingPointId,EndingPointId,DepartureDate,DepartureTime,Hours,CarColor,CarModel,AirConditioner,PetsAllowed,SmokingAllowed,Status,FreeSeats")] TripViewModel tripViewModel)
        {
            if (!ModelState.IsValid || tripViewModel.StartingPointId == tripViewModel.EndingPointId)
            {
                var Error = new ErrorViewModel
                {
                    ImageUrl = "~/assets/customImages/Icons/ErrorIcons/InvalidInputIcon.png",
                    StatusCode = 400,
                    Message = ExceptionMessages.InvalidData
                };
                return View("Error", Error);
            }
            try
            {
                tripViewModel.TripId = id;
                var trip = this.modelMapper.ToModel(tripViewModel);
                trip.TripStatus = tripViewModel.Status;
                await tripService.UpdateAsync(id, trip);
                return this.RedirectToAction("Dashboard", "Users");
            }
            catch (EntityNotFoundException е)
            {
                var Error = new ErrorViewModel
                {
                    ImageUrl = "~/assets/customImages/Icons/ErrorIcons/NotFoundIcon.png",
                    StatusCode = 404,
                    Message = е.Message
                };
                return View("Error", Error);
            }
        }
        //
        [HttpGet]
        [MyAuthorisation(Role = "User,Admin")]
        public async Task<IActionResult> Create(int id)
        {
            var newTrip = new TripViewModel();
            return await TripView(0, newTrip);
        }

        [HttpPost]
        [MyAuthorisation(Role = "User,Admin")]
        public async Task<IActionResult> Create([Bind("StartingPointId,EndingPointId,DepartureDate,DepartureTime,CarColor,CarModel,AirConditioner,PetsAllowed,SmokingAllowed,FreeSeats")] TripViewModel tripViewModel)
        {
            if (!ModelState.IsValid || tripViewModel.StartingPointId == tripViewModel.EndingPointId)
            {
                return await TripView(0, tripViewModel);
            }
            try
            {
                var trip = this.modelMapper.ToModel(tripViewModel);
                var driverId = int.Parse(this.HttpContext.Session.GetString("UserId"));
                trip.DriverId = driverId;
                await tripService.CreateAsync(trip);
                return this.RedirectToAction("Dashboard", "Users");
            }
            catch (EntityNotFoundException е)
            {
                var Error = new ErrorViewModel
                {
                    ImageUrl = "~/assets/customImages/Icons/ErrorIcons/NotFoundIcon.png",
                    StatusCode = 404,
                    Message = е.Message
                };
                return View("Error", Error);
            }
        }
        private async Task<IActionResult> TripView(int tripId, TripViewModel tripViewModel)
        {
            var statuses = GetTripStatuses();
            var addresses = await GetAddresses();
            tripViewModel.StartingPointList = addresses;
            tripViewModel.EndingPointList = addresses;
            tripViewModel.TripStatuses = statuses;
            return View(tripViewModel);
        }
        [HttpGet]
        [MyAuthorisation(Role = "User,Admin")]
        public async Task<IActionResult> ShowCandidates(int tripId)
        {
            var driverId = int.Parse(this.HttpContext.Session.GetString("UserId"));
            var trip = await this.tripService.GetByIdAsync(tripId);
            if (trip.DriverId != driverId)
            {
                var Error = new ErrorViewModel
                {
                    ImageUrl = "~/assets/customImages/Icons/ErrorIcons/AuthenticationIcon.png",
                    StatusCode = 401,
                    Message = ExceptionMessages.YouCannotDoThat
                };
                return View("Error", Error);
            }
            var tripViewModel = modelMapper.ToViewModel(trip);

            return View("_TableCandidates", tripViewModel);
        }
        [HttpPost]
        [MyAuthorisation(Role = "User,Admin")]
        public async Task<IActionResult> ApproveCandidate(int tripId, int userId)
        {
            try
            {
                var result = await this.tripService.ApproveCandidatesAsync(tripId, userId);
                return this.Ok();
            }
            catch (EntityNotFoundException e)
            {
                var Error = new ErrorViewModel
                {
                    ImageUrl = "~/assets/customImages/Icons/ErrorIcons/NotFoundIcon.png",
                    StatusCode = 404,
                    Message = e.Message
                };
                return View("Error", Error);
            }
            catch (InvalidUserOperationException e)
            {
                var Error = new ErrorViewModel
                {
                    ImageUrl = "~/assets/customImages/Icons/ErrorIcons/InvalidOperationIcon.png",
                    StatusCode = 400,
                    Message = e.Message
                };
                return View("Error", Error);
            }
        }
        [HttpPost]
        [MyAuthorisation(Role = "User,Admin")]
        public async Task<IActionResult> DenyCandidate(int tripId, int userId)
        {
            try
            {
                var result = await this.tripService.DeclineCandidatesAsync(tripId, userId);
                return this.Ok();
            }
            catch (EntityNotFoundException e)
            {
                var Error = new ErrorViewModel
                {
                    ImageUrl = "~/assets/customImages/Icons/ErrorIcons/NotFoundIcon.png",
                    StatusCode = 404,
                    Message = e.Message
                };
                return View("Error", Error);
            }
        }
        [HttpPost]
        [MyAuthorisation(Role = "User,Admin")]
        public async Task<IActionResult> RemovePassenger(int tripId, int userId)

FinalProject - Carpooling/Views/Trips/Create.cshtml
@model CarPooling.Models.Trip.TripViewModel;
@{ ViewData["Title"] = "Create Trip"; }
@{ViewData["Method"] = "Create"; }
@{ViewData["Button"] = "Create"; }
<body class=" theme-2">

    <partial name="~/Views/Shared/_HeaderPartial.cshtml" />

    <div class="breadcrumb-div">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <ol class="breadcrumb">
                        <li><a asp-controller="Trips" asp-action="Index">Ride with Tripsy</a></li>
                    </ol>
                </div>
                <div class="col-6">
                    <div class="text-end">
                        <h2>Create a Trip</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container" style="margin-top:5rem;">
        <partial name="~/Views/Trips/_TripForm.cshtml" />
    </div>
    <partial name="~/Views/Shared/_FooterPartialTheme3.cshtml" />
    <div class="modal" id="form-modal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title"></h5>
                </div>
                <div class="modal-body"></div>
            </div>
        </div>
    </div>
    <!-- jQuery -->
    <script src="~/assets/plugins/common/common.min.js"></script>
    <script src="~/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/assets/plugins/OwlCarousel/owl.carousel.min.js"></script>
    <script src="~/assets/plugins/counterup/waypoints.min.js"></script>
    <script src="~/assets/plugins/counterup/jquery.counterup.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <!-- custom scripts -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/custom.js"></script>
</body>

FinalProject - Carpooling/Views/Trips/Edit.cshtml
@model CarPooling.Models.Trip.TripViewModel;
@{ViewData["Title"] = "Edit Trip"; }
@{ViewData["Method"] = "Edit"; }
@{ViewData["Button"] = "Save Changes"; }
<body class=" theme-2">

    <partial name="~/Views/Shared/_HeaderPartial.cshtml" />
    <div class="breadcrumb-div">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <ol class="breadcrumb">
                        <li><a asp-controller="Trips" asp-action="Index">Ride with Tripsy</a></li>
                    </ol>
                </div>
                <div class="col-6">
                    <div class="text-end">
                        <h2 class="page-title" style="text-align: center;">Edit Trip</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container" style="margin-top:5rem;">
        <partial name="~/Views/Trips/_TripForm.cshtml" />
    </div>

    <partial name="~/Views/Shared/_FooterPartialTheme3.cshtml" />

    <div class="modal" id="form-modal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title"></h5>
                </div>
                <div class="modal-body"></div>
            </div>
        </div>
    </div>
    <!-- jQuery -->
    <script src="~/assets/plugins/common/common.min.js"></script>
    <script src="~/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/assets/plugins/OwlCarousel/owl.carousel.min.js"></script>
    <script src="~/assets/plugins/counterup/waypoints.min.js"></script>
    <script src="~/assets/plugins/counterup/jquery.counterup.min.js"></script>
    <!-- custom scripts -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/custom.js"></script>
</body>

FinalProject - Carpooling/Views/Trips/_TableCandidates.cshtml
@model CarPooling.Models.Trip.TripViewModel;

<div id="container-table" class="row small-div">
    <div class="col-lg-12">
        <div class="total-earning-table table-responsive">
            <table class="table align-middle">
                @if (Model.Candidates.Count() > 0)
                {
                    <thead>
                        <tr>
                            <th scope="col">User</th>
                            <th scope="col">Rating</th>
                            <th scope="col">Phone Number</th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var user in Model.Candidates)
                        {
                        <tr>
                            @if (user.ProfilePicture != null)
                            {
                                <th scope="row">
                                    <img class="mе-3 rounded-circle" style="margin-right:1rem!important" height="60" src="@user.ProfilePicture"
                                         alt="partner-img"><span class="fw-light">@user.UserName</span>
                                    </th>
                                }
                                else
                                {
                                    <th scope="row">
                                        <img class="mе-3 rounded-circle" " style="margin-right:1rem!important" height="60" src="/DefaultProfilePic.jpg" alt="partner-img"><span class="fw-light">@user.UserName</span>
                                    </th>
                                }

                            <td>
                                <div class="@user.UserName-rating">
                                    <div class="stars-outer">
                                        <div class="stars-inner" style="width:@((Math.Round(((double)user.RatingPoints / 5 * 100) / 10) * 10) + "%")">
                                        </div>
                                    </div>
                                </div>
                            </td>

                            <td><i class="fas fa-phone"></i> &nbsp; @user.PhoneNumber</td>
                            <td>
                                <a href="#" onclick="EmptyAjaxCandidates('@Url.Action("ApproveCandidate","Trips")',@Model.TripId,@user.UserId)" class="btn-sm btn-secondary">Approve</a>
                                <br />
                                <br />
                                <a href="#" onclick="EmptyAjaxCandidates('@Url.Action("DenyCandidate","Trips")',@Model.TripId,@user.UserId)" class="btn-sm btn-secondary">Deny</a>
                            </td>
                        </tr>
                        }

                    </tbody>
                }
                else
                {
                    <h4 style="text-align: center;">There are no applicants for the trip at this moment!</h4>
                }
            </table>
        </div>
    </div>
</div>

FinalProject - Carpooling/Views/Trips/_TablePassengers.cshtml
@model CarPooling.Models.Trip.TripViewModel;

<div id="container-table-passengers" class="row small-div" style="margin-top: 2rem;">
    <div class="col-lg-12">
        <div class="table-responsive">
            <table class="table align-middle">
                @if (Model.Passengers.Count() > 0)
                {
                    <thead>
                        <tr>
                            <th scope="col">Username</th>
                            <th scope="col">Rating</th>
                            <th scope="col">Phone Number</th>
                            <th></th>

                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var user in Model.Passengers)
                        {
                            <tr>
                                <td>@user.UserName</td>
                                <td>
                                    <div class="@user.UserName-rating">
                                        <div class="stars-outer">
                                            <div class="stars-inner" style="width:@((Math.Round(((double)user.RatingPoints / 5 * 100) / 10) * 10) + "%")">
                                                @user.RatingPoints
                                            </div>
                                        </div>
                                    </div>
                                </td>


                                <td><i class="fas fa-phone-alt"> &nbsp;</i>@user.PhoneNumber</td>
                                <td id="Passengers"><a href="#Passengers" style="color: white;" onclick="EmptyAjaxPassengers('@Url.Action("RemovePassenger", "Trips")',@Model.TripId,@user.UserId)" class="button button-dark">Remove</a></td>
                            </tr>
                        }

                    </tbody>
                }
                else
                {
                    <div style="text-align: center; margin-top: 10px;">
                        <p> There are currently no passingers in the trip!</p>
                    </div>
                }
            </table>
        </div>
    </div>
</div>

FinalProject - Carpooling/Views/Trips/_TripForm.cshtml
@model CarPooling.Models.Trip.TripViewModel;

<form asp-controller="Trips" asp-action="@ViewData["Method"]" method="post" enctype="multipart/form-data" class="margin-bottom">
    <div class="personal-info">
        <div class="personal-details small-div">
            <div class="row">
                <div class="row">
                    <div class="col">
                        <div class="form-group ">
                            <label for="readFirstName">StartingPoint</label>
                            <select asp-for="StartingPointId" asp-items="Model.StartingPointList" class="form-control text-muted">
                                <option value="@Model.StartingPointId"> @Model.StartingPoint </option>
                            </select>
                        </div>
                    </div>
                    <div class="col">
                        <label for="firstName">EndingPoint</label>
                        <select asp-for="EndingPointId" asp-items="Model.EndingPointList" class="form-control text-muted">
                            <option value="@Model.EndingPointId" selected> @Model.EndingPoint </option>
                        </select>
                    </div>
                    <div class="col" style=" display: flex; justify-content: center; align-items: center;">
                        <div class="button button-light" onclick="showInPopup('@Url.Action("Create","Address")','Create')">Create New Location</div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-group">
                        <label for="lastName">Departure</label>
                        @if (ViewData["Method"].ToString() == "Create")
                        {
                            <input asp-for="DepartureDate" type="date" class="form-control text-muted" value="@DateTime.Now.AddHours(1).ToString("yyyy-MM-dd")"
                                   placeholder="@DateTime.Now.AddHours(1).ToString("yyyy-MM-dd")">
                        }
                        else
                        {
                            <input asp-for="DepartureDate" type="date" class="form-control text-muted" value="@Model.DepartureDate.ToString("yyyy-MM-dd")"
                                   min="@DateTime.Now.ToString("yyyy-MM-dd")" placeholder="@Model.DepartureDate.ToString("yyyy-MM-dd")">
                        }
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-group">
                        <label for="lastName">Time</label>
                        <input asp-for="DepartureTime" type="text" class="form-control text-muted" placeholder="@Model.DepartureTime.ToString("HH:mm")">
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-group">
                        <label for="phoneNumber">Number of Free Seats</label>
                        <input asp-for="FreeSeats" type="number" class="form-control text-muted" min="1" placeholder="@Model.FreeSeats">
                    </div>
                </div>@if (ViewData["Method"].ToString() == "Edit")
                {
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label for="phoneNumber">Status</label>
                            <select asp-for="Status" asp-items="Model.TripStatuses" type="text" class="form-control text-muted">
                                <option value="@Model.Status" selected> @Model.Status </option>
                            </select>
                        </div>
                    </div>
                }
                <div class="col-lg-6">
                    <div class="form-group">
                        <label for="phoneNumber">Model Car</label>
                        <input asp-for="CarModel" type="text" class="form-control text-muted" placeholder="@Model.CarModel">
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-group">
                        <label for="phoneNumber">Car Color</label>
                        <input asp-for="CarColor" type="text" class="form-control text-muted" placeholder="@Model.CarColor">
                    </div>
                </div>

                <p></p>
                <div class="list-group mx-0">
                    <label class="list-group-item d-flex gap-2">
                        @if (Model.AirConditioner)
                        {
                            <input class="form-check-input flex-shrink-0" asp-for="AirConditioner" type="checkbox" checked value="true">

                        }
                        else
                        {
                            <input class="form-check-input flex-shrink-0" asp-for="AirConditioner" type="checkbox" value="true">

                        }
                        <span>
                            AirConditioner
                            <small class="d-block text-muted">Select if you have air conditioning pets in your vehicle.</small>
                        </span>
                    </label>
                    <label class="list-group-item d-flex gap-2">
                        @if (Model.SmokingAllowed)
                        {
                            <input class="form-check-input flex-shrink-0" asp-for="SmokingAllowed" type="checkbox" checked value="true">
                        }
                        else
                        {
                            <input class="form-check-input flex-shrink-0" asp-for="SmokingAllowed" type="checkbox" value="true">
                        }
                        <span>
                            Smoking
                            <small class="d-block text-muted">Select if you allow smoking in your vehicle.</small>
                        </span>
                    </label>

                    <label class="list-group-item d-flex gap-2">
                        @if (Model.PetsAllowed)
                        {
                            <input class="form-check-input flex-shrink-0" asp-for="PetsAllowed" type="checkbox" checked value="true">
                        }
                        else
                        {
                            <input class="form-check-input flex-shrink-0" asp-for="PetsAllowed" type="checkbox" value="true">
                        }
                        <span>
                            Pets
                            <small class="d-block text-muted">Select if you allow pets in your vehicle.</small>
                        </span>
                    </label>

                    @if (@ViewData["Method"].ToString() == "Edit")
                    {
                        @await Html.PartialAsync("_TablePassengers", Model);
                    }
                </div>
                <p></p>

                <div class="col-lg-12">
                    <button type="submit" class="button button-light"><span>@ViewData["Button"]</span></button>
                </div>

            </div>
        </div>
    </div>
</form>