FinalProject - Carpooling/Models/Rating/RatingViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace CarPooling.Models.Rating
{
    public class RatingViewModel
    {
        public int RatedUserId { get; set; }
        public string RatedUserUserName { get; set; }
        public int TripId { get; set; }
        public int RatingUserId { get; set; }
        [Required]
        [Range(1, 5, ErrorMessage = "Points must be between {0} and {1} !")]
        public int RatingPoints { get; set; }
        [Required]
        [StringLength(500, MinimumLength = 5, ErrorMessage = "Comment must be between {0} and {1} characters.")]
        public string Comment { get; set; }
    }
}

FinalProject - Carpooling/Controllers/RatingsController.cs
using CarPooling.Helpers;
using CarPooling.Models;
using CarPooling.Models.Rating;
using CarPooling.Service.Constants;
using CarPooling.Service.Services.Contracts;
using CarPooling.Services.Exceptions;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace CarPooling.Controllers
{
    public class RatingsController : Controller
    {
        private readonly IRatingService ratingService;
        private readonly IWebModelMapper modelMapper;

        public RatingsController(IRatingService ratingService, IWebModelMapper modelMapper)
        {
            this.ratingService = ratingService;
            this.modelMapper = modelMapper;
        }
        [HttpGet]
        [MyAuthorisation(Role = "User,Admin")]
        public async Task<IActionResult> Create(int ratedUserId, string username, int tripId)
        {
            var ratingView = new RatingViewModel();
            ratingView.RatedUserId = ratedUserId;
            ratingView.TripId = tripId;
            ratingView.RatedUserUserName = username;
            return this.View(ratingView);
        }
        [HttpPost]
        [MyAuthorisation(Role = "User,Admin")]
        public async Task<IActionResult> Create([Bind("RatedUserId,RatingPoints,Comment,TripId")] RatingViewModel ratingViewModel)
        {
            if (!ModelState.IsValid)
            {
                var Error = new ErrorViewModel
                {
                    ImageUrl = "~/assets/customImages/Icons/ErrorIcons/InvalidInputIcon.png",
                    StatusCode = 409,
                    Message = ExceptionMessages.InvalidData
                };
                return View("Error", Error);
            }
            try
            {
                var ratingUserId = int.Parse(this.HttpContext.Session.GetString("UserId"));
                ratingViewModel.RatingUserId = ratingUserId;
                var rating = modelMapper.ToModel(ratingViewModel);
                await this.ratingService.CreateAsync(rating);
                int id = ratingViewModel.TripId;
                return RedirectToAction("Details", "Trips", new { id = id });
            }
            catch (DuplicateEntityException e)
            {
                var Error = new ErrorViewModel
                {
                    ImageUrl = "~/assets/customImages/Icons/ErrorIcons/DuplicateIcon.png",
                    StatusCode = 409,
                    Message = e.Message
                };
                return View("Error", Error);
            }
        }
    }
}

FinalProject - Carpooling/Views/Ratings/Create.cshtml
@model CarPooling.Models.Rating.RatingViewModel
<div class="row">
    <div class="row">
        <form asp-controller="Ratings" asp-action="Create">
            <div>
                <div class="row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label for="firstName">Rating User</label>
                            <input type="text" class="form-control text-muted" id="firstName" readonly placeholder="@Model.RatedUserUserName" value="@Model.RatedUserUserName">
                            <input asp-for="RatedUserId" hidden type="text" class="form-control text-muted" id="firstName" readonly value="@Model.RatedUserId">
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label for="firstName">Rating from 1 to 5 </label>
                            <span asp-validation-for="RatingPoints" class="form-error"></span>
                            <input asp-for="RatingPoints" type="number" class="form-control text-muted" min="1" max="5" placeholder="Input Rating">
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <span asp-validation-for="Comment" class="form-error"></span>
                        <textarea asp-for="Comment" class="form-control" id="Message" placeholder="Input your Comment"></textarea>
                        <input asp-for="TripId" hidden type="number" class="form-control text-muted" id="firstName" readonly value="@Model.TripId">
                    </div>
                    <div class="col-lg-12">
                        <button type="submit" class="button button-dark tiny">Create</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>