FinalProject - Carpooling/Controllers/TripsController.cs
using CarPooling.Data.Models.Enums;
using CarPooling.Helpers;
using CarPooling.Models;
using CarPooling.Models.Trip;
using CarPooling.Service.Constants;
using CarPooling.Service.Services.Contracts;
using CarPooling.Services.Exceptions;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CarPooling.Controllers
{
    public class TripsController : Controller
    {
        private readonly ITripService tripService;
        private readonly IUserService userService;
        private readonly IWebModelMapper modelMapper;

        public TripsController(ITripService tripService, IUserService userService, IWebModelMapper modelMapper)
        {
            this.tripService = tripService;
            this.userService = userService;
            this.modelMapper = modelMapper;
        }
        public async Task<IActionResult> Index()
        {
            var paginatedTrips = await tripService.GetAllPaginatedTripsAsync(1);
            return View(paginatedTrips);
        }
        [HttpPost]
        public async Task<IActionResult> GetAllPaginatedTrips(int page)
        {
            var result = await tripService.GetAllPaginatedTripsAsync(page);
            return Json(new { html = await Renderer.RenderViewAsync(this, "_Table", result, true) });
        }

        public async Task<IActionResult> Details(int id)
        {
            try
            {
                if (HttpContext.Session.Keys.Contains("UserId"))
                {
                    var userId = int.Parse(this.HttpContext.Session.GetString("UserId"));
                    var user = this.userService.GetByIdAsync(userId);
                    RedirectToAction("SetSessionStrings", "Account", await user);
                }
                var trip = await tripService.GetByIdAsync(id);
                var tripViewModel = this.modelMapper.ToViewModel(trip);

                var weatherModel = await tripService.GetWeather(trip);
                tripViewModel.Weather = weatherModel;

                return View(tripViewModel);
            }
            catch (EntityNotFoundException e)
            {
                var Error = new ErrorViewModel
                {
                    ImageUrl = "~/assets/customImages/Icons/ErrorIcons/NotFoundIcon.png",
                    StatusCode = 404,
                    Message = e.Message
                };
                return View("Error", Error);
            }
        }

        [HttpGet]
        [MyAuthorisation(Role = "User,Admin")]
        public async Task<IActionResult> Edit(int id)
        {
            var driverId = int.Parse(this.HttpContext.Session.GetString("UserId"));
            try
            {
                var tripToUpdate = await tripService.GetByIdAsync(id);
                if (tripToUpdate.DriverId != driverId)
                {
                    var Error = new ErrorViewModel
                    {
                        ImageUrl = "~/assets/customImages/Icons/ErrorIcons/AuthenticationIcon.png",
                        StatusCode = 401,
                        Message = ExceptionMessages.YouCannotDoThat
                    };
                    return View("Error", Error);
                }
                var tripViewModel = modelMapper.ToViewModel(tripToUpdate);
                return await TripView(id, tripViewModel);
            }
            catch (EntityNotFoundException e)
            {
                var Error = new ErrorViewModel
                {
                    ImageUrl = "~/assets/customImages/Icons/ErrorIcons/NotFoundIcon.png",
                    StatusCode = 404,
                    Message = e.Message
                };
                return View("Error", Error);
            }
        }

        [HttpPost]
        [MyAuthorisation(Role = "User,Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("StartingPointId,EndingPointId,DepartureDate,DepartureTime,Hours,CarColor,CarModel,AirConditioner,PetsAllowed,SmokingAllowed,Status,FreeSeats")] TripViewModel tripViewModel)
        {
            if (!ModelState.IsValid || tripViewModel.StartingPointId == tripViewModel.EndingPointId)
            {
                var Error = new ErrorViewModel
                {
                    ImageUrl = "~/assets/customImages/Icons/ErrorIcons/InvalidInputIcon.png",
                    StatusCode = 400,
                    Message = ExceptionMessages.InvalidData
                };
                return View("Error", Error);
            }
            try
            {
                tripViewModel.TripId = id;
                var trip = this.modelMapper.ToModel(tripViewModel);
                trip.TripStatus = tripViewModel.Status;
                await tripService.UpdateAsync(id, trip);
                return this.RedirectToAction("Dashboard", "Users");
            }
            catch (EntityNotFoundException е)
            {
                var Error = new ErrorViewModel
                {
                    ImageUrl = "~/assets/customImages/Icons/ErrorIcons/NotFoundIcon.png",
                    StatusCode = 404,
                    Message = е.Message
                };
                return View("Error", Error);
            }
        }
        //
        [HttpGet]
        [MyAuthorisation(Role = "User,Admin")]
        public async Task<IActionResult> Create(int id)
        {
            var newTrip = new TripViewModel();
            return await TripView(0, newTrip);
        }

        [HttpPost]
        [MyAuthorisation(Role = "User,Admin")]
        public async Task<IActionResult> Create([Bind("StartingPointId,EndingPointId,DepartureDate,DepartureTime,CarColor,CarModel,AirConditioner,PetsAllowed,SmokingAllowed,FreeSeats")] TripViewModel tripViewModel)
        {
            if (!ModelState.IsValid || tripViewModel.StartingPointId == tripViewModel.EndingPointId)
            {
                return await TripView(0, tripViewModel);
            }
            try
            {
                var trip = this.modelMapper.ToModel(tripViewModel);
                var driverId = int.Parse(this.HttpContext.Session.GetString("UserId"));
                trip.DriverId = driverId;
                await tripService.CreateAsync(trip);
                return this.RedirectToAction("Dashboard", "Users");
            }
            catch (EntityNotFoundException е)
            {
                var Error = new ErrorViewModel
                {
                    ImageUrl = "~/assets/customImages/Icons/ErrorIcons/NotFoundIcon.png",
                    StatusCode = 404,
                    Message = е.Message
                };
                return View("Error", Error);
            }
        }
        private async Task<IActionResult> TripView(int tripId, TripViewModel tripViewModel)
        {
            var statuses = GetTripStatuses();
            var addresses = await GetAddresses();
            tripViewModel.StartingPointList = addresses;
            tripViewModel.EndingPointList = addresses;
            tripViewModel.TripStatuses = statuses;
            return View(tripViewModel);
        }
        [HttpGet]
        [MyAuthorisation(Role = "User,Admin")]
        public async Task<IActionResult> ShowCandidates(int tripId)
        {
            var driverId = int.Parse(this.HttpContext.Session.GetString("UserId"));
            var trip = await this.tripService.GetByIdAsync(tripId);
            if (trip.DriverId != driverId)
            {
                var Error = new ErrorViewModel
                {
                    ImageUrl = "~/assets/customImages/Icons/ErrorIcons/AuthenticationIcon.png",
                    StatusCode = 401,
                    Message = ExceptionMessages.YouCannotDoThat
                };
                return View("Error", Error);
            }
            var tripViewModel = modelMapper.ToViewModel(trip);

            return View("_TableCandidates", tripViewModel);
        }
        [HttpPost]
        [MyAuthorisation(Role = "User,Admin")]
        public async Task<IActionResult> ApproveCandidate(int tripId, int userId)
        {
            try
            {
                var result = await this.tripService.ApproveCandidatesAsync(tripId, userId);
                return this.Ok();
            }
            catch (EntityNotFoundException e)
            {
                var Error = new ErrorViewModel
                {
                    ImageUrl = "~/assets/customImages/Icons/ErrorIcons/NotFoundIcon.png",
                    StatusCode = 404,
                    Message = e.Message
                };
                return View("Error", Error);
            }
            catch (InvalidUserOperationException e)
            {
                var Error = new ErrorViewModel
                {
                    ImageUrl = "~/assets/customImages/Icons/ErrorIcons/InvalidOperationIcon.png",
                    StatusCode = 400,
                    Message = e.Message
                };
                return View("Error", Error);
            }
        }
        [HttpPost]
        [MyAuthorisation(Role = "User,Admin")]
        public async Task<IActionResult> DenyCandidate(int tripId, int userId)
        {
            try
            {
                var result = await this.tripService.DeclineCandidatesAsync(tripId, userId);
                return this.Ok();
            }
            catch (EntityNotFoundException e)
            {
                var Error = new ErrorViewModel
                {
                    ImageUrl = "~/assets/customImages/Icons/ErrorIcons/NotFoundIcon.png",
                    StatusCode = 404,
                    Message = e.Message
                };
                return View("Error", Error);
            }
        }
        [HttpPost]
        [MyAuthorisation(Role = "User,Admin")]
        public async Task<IActionResult> RemovePassenger(int tripId, int userId)

FinalProject - Carpooling/ViewComponents/ChatViewComponent.cs
using CarPooling.Service.Services.Contracts;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace CarPooling.ViewComponents
{
    public class ChatViewComponent : ViewComponent
    {
        private readonly IChatService chatService;
        public ChatViewComponent(IChatService chatService)
        {
            this.chatService = chatService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var messanges = await this.chatService.GetAllMessagesAsync();
            return View(messanges);
        }
    }
}

FinalProject - Carpooling/Views/Shared/_FooterPartialTheme1.cshtml
<footer class="footer-div theme-1">
    <div class="footer-shape">
        <svg data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 120" preserveAspectRatio="none">
            <path d="M985.66,92.83C906.67,72,823.78,31,743.84,14.19c-82.26-17.34-168.06-16.33-250.45.39-57.84,11.73-114,31.07-172,41.86A600.21,600.21,0,0,1,0,27.35V120H1200V95.8C1132.19,118.92,1055.71,111.31,985.66,92.83Z" class="shape-fill"></path>
        </svg>
    </div>

    <div class="footer-nav-div div-padding theme-1">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-sm-6  flex-justified">
                    <div class="footer-brand">
                        <a href="index.html"><img src="~/assets/customImages/logoSmall/LogoForFooter.png" alt="Logo"></a>
                    </div>
                    <div class="footer-text">
                        <p>Nulla justo neque, tincidunt id bibendum a, rhoncus et eros. Vestibulum commodo diam ut risus pulvinar consequat vitae a dui. Vivamus sed molestie diam. Maecenas vitae enim lacus.</p>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6 flex-justified" style="align-items: center;">
                    <h4>Useful links</h4>
                    <nav class="footer-navigation" style="line-height: 2.2;">
                        <ul>
                            <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                            <li><a asp-controller="Home" asp-action="About">About</a></li>
                            <li><a asp-controller="Trips" asp-action="Index">Trips</a></li>
                        </ul>
                    </nav>
                </div>
                <div class="col-lg-3 col-sm-6  flex-justified">
                    <h4>Head Office</h4>
                    <address class="company-address">
                        <p class="m-b-8">Alexander Malinov Campus X - Sofia, Bulgaria </p>
                        <p class="m-b-8">Phone Number : (+1) 123 4567 890</p>
                        <p class="m-b-8">Email Address :Tripsy@gmail.com</p>
                    </address>
                </div>
                <div class="col-lg-3 col-sm-6  flex-justified">
                    <div class="cta-button">
                        <a asp-controller="Account" asp-action="Register" class="button button-dark">Sign Up</a>
                        <a asp-controller="Account" asp-action="Login" class="button button-dark">Sign In</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="copyright-div">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <p>&copy; Copyright 2021 - Tripsy. All Right Reserved.</p>
                </div>
            </div>
        </div>
    </div>
</footer>

FinalProject - Carpooling/Views/Shared/_FooterPartialTheme3.cshtml
<footer class="theme-3">

    <div class="footer-nav-div div-padding theme-2">
        <div class="container">
            <div class="row">
                <div class="col-lg-3  flex-justified">
                    <div class="footer-brand">
                        <a asp-controller="Home" asp-action="Index"><img src="~/assets/customImages/logoSmall/LogoForFooter.png" alt="logo"></a>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6  flex-justified" style="align-items: center;">
                    <h4>Useful links</h4>
                    <nav class="footer-navigation" style="line-height: 2.2;">
                        <ul>
                            <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                            <li><a asp-controller="Home" asp-action="About">About</a></li>
                            <li><a asp-controller="Trips" asp-action="Index">Trips</a></li>
                        </ul>
                    </nav>
                </div>
                <div class="col-lg-3 col-sm-6  flex-justified">
                    <h4>Head Office</h4>
                    <address class="company-address">
                        <p class="m-b-8">Alexander Malinov Campus X - Sofia, Bulgaria </p>
                        <p class="m-b-8">Phone Number : (+1) 123 4567 890</p>
                        <p class="m-b-8">Email Address :Tripsy@gmail.com</p>
                    </address>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <div class="cta-button">
                        <a asp-controller="Account" asp-action="Register" class="button button-dark">Sign Up</a>
                        <a asp-controller="Account" asp-action="Login" class="button button-dark">Sign In</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="copyright-div theme-2  flex-justified">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <p>&copy; Copyright 2021 - Tripsy. All Right Reserved.</p>
                </div>
            </div>
        </div>
    </div>
</footer>

FinalProject - Carpooling/Views/Shared/_HeaderPartial.cshtml
@using Microsoft.AspNetCore.Http;
@{
    this.ViewData["IsAuthenticated"] = this.Context.Session.Keys.Contains("CurrentUser");
    this.ViewData["UserId"] = this.Context.Session.GetString("UserId");
    this.ViewData["CurrentUser"] = this.Context.Session.GetString("CurrentUser");
    this.ViewData["UserRole"] = this.Context.Session.GetString("UserRole");
}
@await Component.InvokeAsync("Chat")
<header class="theme-1">
    <div class="header__upper">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <div class="header__upper--left">
                        <div class="logo">
                            <a asp-controller="Home" asp-action="Index"><img height="45" src="~/assets/customImages/logoSmall/logoSmallColor.png" alt=""></a>
                        </div>
                        <div class="search-bar">
                            <form class="form">
                                <span class="icon icon-left"><i class="fas fa-map-marker-alt"></i></span>
                                <input class="form-control" type="search" name="destination" placeholder="Tell us your destination" id="search-bar">
                                <button asp-controller="Trips" asp-action="FilterByDestination" class="button button-dark" type="submit"><i class="fas fa-search"></i></button>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="header__upper--right">
                        <nav class="navigation">
                            <ul>
                                <li><a asp-controller="Trips" asp-action="Index">Trips</a></li>
                                <li><a asp-controller="Home" asp-action="About">About</a></li>
                                <li><a asp-controller="Home" asp-action="Contact">Contact Us</a></li>
                                <li><a asp-controller="Users" asp-action="Index">Users</a></li>
                                @if (!(bool)ViewData["IsAuthenticated"])
                                {
                                    <li><a asp-controller="Account" asp-action="Login">Sign in</a></li>
                                    <li><a asp-controller="Account" asp-action="Register">Sign Up</a></li>
                                }
                                else
                                {
                                    <li>
                                        <div class="media-body">
                                            <h6 class="m-0"><a asp-controller="Users" asp-action="Dashboard">@this.ViewData["CurrentUser"].ToString()</a></h6>
                                        </div>
                                    </li>
                                    <li><a asp-controller="Account" asp-action="Logout">Log Out</a></li>
                                }
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

FinalProject - Carpooling/Views/Shared/_IconsPartial.cshtml
@model CarPooling.Service.ResponseModels.TripResponseModel

<td>
    @if (Model.AirConditioner.Equals(true))
    {<img height="24" src="~/assets/customImages/Icons/AirConditioner.png" /><span>&nbsp;</span> }
    else
    {<img height="24" src="~/assets/customImages/Icons/NoAirConditioner.png" /><span>&nbsp;</span> }
    @if (Model.SmokingAllowed.Equals(true))
    {<img height="24" src="~/assets/customImages/Icons/Smoking.png"/><span>&nbsp;</span> }
    else
    {<img height="24" src="~/assets/customImages/Icons/NoSmoking.png" /><span>&nbsp;</span> }
    @if (Model.PetsAllowed.Equals(true))
    {<img height="24" src="~/assets/customImages/Icons/PetsAllowed.png" />}
    else
    {<img height="24" src="~/assets/customImages/Icons/PetsNotAllowed.png" />}
</td>

FinalProject - Carpooling/Views/Shared/_Layout.cshtml
<!doctype html>
<html class="no-js" lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Tripsy - @ViewData["Title"]</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/png" sizes="16x16" href="~/favicon.png" />
    <link rel="apple-touch-icon" href="icon.png">
    <link rel="stylesheet" href="~/assets/plugins/OwlCarousel/owl.carousel.min.css" />
    <link rel="stylesheet" href="~/assets/plugins/metismenu/css/metisMenu.min.css" />
    <link rel="stylesheet" href="~/main/css/style.css" />
    <link rel="stylesheet" href="~/main/css/custom2.css" />
    <link rel="stylesheet" href="~/fonts_awesome/css/all.css" />

</head>
    @RenderBody()
</html>